version: '3.8'

services:
  api:
    build: .
    ports:
      - "6656:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      # - OCR_API_URL=https://ocr.example.com/
    depends_on:
      - mongodb
    volumes:
      - ./app:/code/app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge